name: Display Supported PHP Versions

on:
  push:
    branches:
      - main

jobs:
  display_versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read supported versions
        id: read-versions
        run: |
          echo "[]" > versions.json
          while IFS= read -r version; do
            echo "{\"label\": \"$version\", \"value\": \"$version\"}," >> versions.json
          done < supported_versions.txt

      - name: Remove trailing comma
        run: sed -i '$ s/,$//' versions.json

      - name: Commit versions.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update supported PHP versions"
          branch: main
          files: |
            versions.json
